#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

img="$(./bocker init ~/base-image | awk '{print $2}')"
./bocker images | grep -qw "$img"
[[ "$?" == 0 ]]

./bocker run "$img" wget
ps="$(./bocker ps | grep 'wget' | awk '{print $1}')"
logs="$(./bocker logs "$ps")"
./bocker rm "$ps"
[[ "$logs" == *"wget: command not found"* ]]

./bocker run "$img" yum install -y wget
ps="$(./bocker ps | grep 'yum install -y wget' | awk '{print $1}')"
./bocker commit "$ps" "$img"

./bocker run "$img" wget -qO- http://httpbin.org/get
ps="$(./bocker ps | grep 'wget -qO- http://httpbin.org/get' | awk '{print $1}')"
logs="$(./bocker logs "$ps")"
[[ "$logs" == *'http://httpbin.org/get'* ]]
